apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-flask-app
spec:
  containers:
  - name: kubernetes-flask-app-ctr
    image: sadalvi/kubernetes-flask-app:latest
    env:
    - name: SQLALCHEMY_DATABASE_URI
      value: postgresql://postgres:postgres@localhost:5432/mydatabase
    ports:
      - containerPort: 5000
    imagePullPolicy: always

